spring:
  datasource:
    url: jdbc:postgresql://ep-spring-pine-b5qcmvqp-pooler.c-7.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: ${NEON_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
